[project]
name = "datastore360"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abd0id", email = "abdellah.idfath.dev@gmail.com" }
]
requires-python = ">=3.10, <3.15"
dependencies = [
    "apache-airflow>=3.3.1",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.9",
    "pandas<3",
    "scipy>=1.4.1,<1.17",
    "setuptools<81",
    "ydata-profiling>=4.18.4",
]

[project.scripts]
datastore360 = "datastore360:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
